# Generated by Django 3.2.10 on 2021-12-14 06:10

from django.db import migrations, models
import django.db.models.deletion
import selections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('price', models.FloatField(validators=[selections.models.validate_decimals])),
                ('outcome', models.CharField(choices=[('unsettled', 'Unsettled'), ('void', 'Void'), ('lose', 'Lose'), ('win', 'Win')], max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventsmodel')),
            ],
            options={
                'db_table': 'selections',
            },
        ),
    ]
