# Generated by Django 3.2.10 on 2021-12-14 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('type', models.CharField(choices=[('preplay', 'Preplay'), ('inplay', 'Inplay')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], max_length=100)),
                ('scheduled_start', models.DateTimeField()),
                ('actual_start', models.DateTimeField(null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportsmodel')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
